//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibEasySave.Res {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibEasySave.Res.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///  &quot;_activLang&quot;: 0,
        ///  &quot;_tralstedTexts&quot;: {
        ///    &quot;EN&quot;: {
        ///      &quot;_eLangCode_EN&quot;: &quot;EN : English&quot;,
        ///      &quot;_eLangCode_FR&quot;: &quot;FR : French&quot;,
        ///      &quot;_eSavingMode_FULL&quot;: &quot;FULL : copy all files and overwrite the same files&quot;,
        ///      &quot;_eSavingMode_DIFF&quot;: &quot;DIFF : copy only files who aren&apos;t present in destination folder&quot;,
        ///      &quot;_welcome&quot;: &quot;welcome on a ProSoft Software : EasySave&quot;,
        ///      &quot;_bye&quot;: &quot;Thank you for your trust&quot;,
        ///      &quot;_disableText&quot;: &quot;DISABLE&quot;,
        ///      &quot;_answerModelView&quot;: &quot;output&quot;,
        ///      &quot;_failMsg&quot;: &quot;F [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string LangData {
            get {
                return ResourceManager.GetString("LangData", resourceCulture);
            }
        }
    }
}
